[package]
name = "bevy_voxels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
rand = "0.8.5"
once_cell = "1.12.1"
block-mesh = "0.2.0"
ndshape = "0.3.0"
ilattice = "0.1.0"